## libraries and function

In [ ]:
!pip install fancyimpute

  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 7.8 MB/s eta 0:00:00
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29881 sha256=c6f4cfda74d8264658f4cac3fb996293fd14220977e972ef9eda10105d6b07c9
  Stored in directory: /root/.cache/pip/wheels/7b/0c/d3/ee82d1fbdcc0858d96434af108608d01703505d453720c84ed
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11330 sha256=436d3de13f78702b18254c5f29a5b0544998eea12c4f7eb2225eefde489099de
  Stored in directory: /root/.cache/pip/wheels/46/06/a5/45a724630562413c374e29c08732411d496092408b3a7bf754
Successfully built fancyimpute knnimpute


In [ ]:
!pip install DistributedMissForest

  Preparing metadata (setup.py) ... done
  Created wheel for DistributedMissForest: filename=DistributedMissForest-1.4-py3-none-any.whl size=17470 sha256=90edc0e96bb98bdd3069caf19e59c1ab7b0ea2808a78ed84071a337e1a74c054
  Stored in directory: /root/.cache/pip/wheels/62/93/ad/606370d3635fc2b977fafeeccd59929f886b09f19d4386e0ac
Successfully built DistributedMissForest


In [ ]:
!pip install missingpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.1/49.1 kB 1.6 MB/s eta 0:00:00


In [ ]:
!pip install MissForest

In [ ]:
import sklearn.neighbors._base
import sys
sys.modules['sklearn.neighbors.base'] = sklearn.neighbors._base
# !pip install impyute
# !pip install fancyimpute
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as skLDA
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy import stats
import numpy as np
# import impyute as impy
from fancyimpute import SoftImpute#, MatrixFactorization
import pandas as pd
import time
import math
# from missingpy
from missforest.missforest import MissForest
from sklearn.model_selection import train_test_split
# from functions.phf import *
# from functions.da import *
# from functions.dper import *
from numpy.linalg import norm, inv
# from xgbimputer import XGBImputer

In [ ]:
from sklearn import datasets
from sklearn.preprocessing import LabelEncoder, StandardScaler
from scipy import stats
import numpy as np
import pandas as pd
import time
!pip install pandas

In [ ]:
def diag_term(i, X, y, G):
    arr0 = X[:, i]
    arr = arr0[~np.isnan(arr0)]
    y_arr = y[~np.isnan(arr0)]

    _, counts = np.unique(y_arr, return_counts = True)
    ind = np.insert(np.cumsum(counts), 0, 0)

    return sum([(ind[g] - ind[g - 1]) * np.var(arr[y_arr == g - 1]) for
                g in range(1, G + 1)]) / len(y_arr)


def dper(X, y, G):
    '''
    X: input, should be a numpy array
    y: label
    G: number of classes
    output:
    - mus: each row is a class mean
    - S: common covariance matrix of class 1,2,..., G
    '''
    epsilon = 1e-5  # define epsilon to put r down to 0 if r < epsilon
    n, p = X.shape[0], X.shape[1]

    mus = np.array(
        [np.nanmean(X[y == g, :], axis = 0) for g in range(G)]).T  # so that each column is the mean of a class

    S = np.diag([diag_term(i, X, y, G) for i in range(p)])

    for i in range(p):
        for j in range(i):
            mat = X[:, [i, j]]

            # drop rows with NA
            idx = ~np.isnan(mat).any(axis = 1)
            mat, y_arr = mat[idx], y[idx]

            _, counts = np.unique(y_arr, return_counts = True)
            ind = np.insert(np.cumsum(counts), 0, 0)

            m_g = counts

            A = len(y_arr)

            scaled_mat = [mat[y_arr == g, :] - mus[[i, j], g] for g in range(G)]

            q = lambda g: np.dot(scaled_mat[g][:, 0], scaled_mat[g][:, 0])
            s11 = sum(map(q, range(G)))
            q = lambda g: np.dot(scaled_mat[g][:, 1], scaled_mat[g][:, 1])
            s22 = sum(map(q, range(G)))
            d = lambda g: np.dot(scaled_mat[g][:, 0], scaled_mat[g][:, 1])
            s12 = sum(map(d, range(G)))

            start_solve = time.time()
            B = S[i, i] * S[j, j] * A - s22 * S[i, i] - s11 * S[j, j]
            coefficient = [-A, s12, B, s12 * S[i, i] * S[j, j]]
            r = np.roots(coefficient)

            r = r[abs(np.imag(r)) < epsilon]
            r = np.real(r)
            r[abs(r) < epsilon] = 0

            if len(r) > 1:
                condi_var = S[j, j] - r ** 2 / S[i, i]
                eta = -A * np.log(condi_var) - (S[j, j] - 2 * r / S[i, i] * s12 +
                                                r ** 2 / S[i, i] ** 2 * s11) / condi_var
                # if condi_var <0 then eta = NA. in practice, it's impossible for cov to be negative
                #  therefore, we drop NA elements of eta
                r = r[eta == max(eta[~np.isnan(eta)])]

            if len(r) > 1:
                w = [m_g[g - 1] * np.cov(mat[ind[g - 1]:ind[g], ], rowvar = False) for
                     g in range(1, G + 1)]
                w = np.sum(w, axis = 0)
                r = r[np.abs(r - w[0, 1]).argmin()]  # choose r that is w[0,1]

            S[i, j] = S[j, i] = r
    return [mus, S]

In [ ]:
# @title
import numpy as np

def generate_nan(X, non_missing , missing_rate):
    X_copy=np.copy(X)

    X_non_missing_col = X_copy[:, non_missing]
    X1_missing = X_copy[:, [i for i in range(X.shape[1]) if i not in non_missing]]

    X_non_missing_row = X1_missing[non_missing]
    X_missing = X1_missing[len(non_missing):(X.shape[0]+1)]

    XmShape = X_missing.shape
    na_id = np.random.randint(0, X_missing.size, round(missing_rate * X_missing.size))
    X_nan = X_missing.flatten()
    X_nan[na_id] = np.nan
    X_nan = X_nan.reshape(XmShape)

    X1_nan = np.vstack((X_non_missing_row, X_nan))
    X_nan = np.hstack((X_non_missing_col, X1_nan))
    return X_nan

def PHF(Xm, y, G):
    p = Xm.shape[1]
    non_missing_id = np.where(np.sum(np.isnan(Xm), axis = 0) == 0)
    q = max(non_missing_id)[-1] + 1
    # initialize the parameter with 0s
    S = np.zeros((p, p))
    # estimating the parameter for the fully observed features
    mu = np.array([np.nanmean(Xm[y == g, :], axis = 0) for g in range(G)]).T  # the mean is stored column
    S[:q, :q] = sum([sum(y == g) * np.cov(Xm[y == g, :q], rowvar = False, ddof = 0) for g in range(G)]) / len(y)
    # estimating the parameter in step 2 of the algorithm:
    for j in range(q, p):
        id = ~np.isnan(Xm[:, j])
        Xfj = Xm[id, :][:, np.hstack((range(q), j))]
        yfj = y[id]
        covm = sum([sum(yfj == g) * np.cov(Xfj[yfj == g, :], rowvar = False, ddof = 0) for g in range(G)]) / len(yfj)
        Q = covm[-1, range(q)]  # row vector
        P = np.matmul(Q, np.linalg.inv(covm[:q, :q]))
        S[j, range(q)] = np.matmul(P, S[:q, :q])

        Xj, yj = Xm[id, j], y[id]
        cal_S = lambda g: np.dot(Xj[yj == g] - mu[j, g], Xj[yj == g] - mu[j, g])
        S[j, j] = sum(map(cal_S, range(G)))/len(yj)

        S[j, range(q, j)] = np.array([dper_sigij(Xm, y, G, mu, i, j, S[i, i], S[j, j]) for i in range(q, j)]).flatten()
        S[:, j] = S[j, :].T
    return mu, S


def dper_sigij(X, y, G, mus, i, j, sigii, sigjj):
    """
    X: input, should be a numpy array
    y: label
    G: number of classes
    i, j: index of the column
    sigii: sigma_ii
    sigjj: sigma_jj
    """
    epsilon = 1e-5  # define epsilon to put r down to 0 if r < epsilon

    mat = X[:, [i, j]]

    # drop rows with NA
    idx = ~np.isnan(mat).any(axis = 1)
    mat, y_arr = mat[idx], y[idx]

    A = len(y_arr)
    scaled_mat = [mat[y_arr == g, :] - mus[[i, j], g] for g in range(G)]
    q = lambda g: np.dot(scaled_mat[g][:, 0], scaled_mat[g][:, 0])
    s11 = sum(map(q, range(G)))
    q = lambda g: np.dot(scaled_mat[g][:, 1], scaled_mat[g][:, 1])
    s22 = sum(map(q, range(G)))
    d = lambda g: np.dot(scaled_mat[g][:, 0], scaled_mat[g][:, 1])
    s12 = sum(map(d, range(G)))
    B = sigii * sigjj * A - s22 * sigii - s11 * sigjj
    coefficient = [-A, s12, B, s12 * sigii * sigjj]
    r = np.roots(coefficient)

    r = r[abs(np.imag(r)) < epsilon]
    r = np.real(r)
    r[abs(r) < epsilon] = 0

    if len(r) > 1:
        condi_var = sigjj - r ** 2 / sigii
        # print('condi_var',condi_var)
        eta = -A * np.log(condi_var) - (sigjj - 2 * r / sigii * s12 +
                                        r ** 2 / sigii ** 2 * s11) / condi_var
        # if condi_var <0 then eta = NA. in practice, it's impossible for cov to be negative
        #  therefore, we drop NA elements of eta
        r = r[eta == max(eta[~np.isnan(eta)])]

    if len(r) > 1:
        r = r[np.abs(r - s12 / A).argmin()]  # select r that is closet to w[0,1]

    return r


def PHF1Cl(Xm):
  p = Xm.shape[1]
  non_missing_id = np.where(np.sum(np.isnan(Xm), axis=0)==0)
  q = max(non_missing_id)[-1] + 1
  # initialize the parameter with 0s
  mu = np.zeros((p, 1))
  S = np.zeros((p,p))
  # estimating the parameter for the fully observed features
  mu[:q,:] = np.mean(Xm[:,:q], axis = 0).reshape((-1,1)) # the mean is stored column
  S[:q,:q] =   np.cov(Xm[:, :q], rowvar = False, ddof = 0)
  # estimating the parameter in step 2 of the algorithm:
  for j in range(q,p):
    id = ~np.isnan(Xm[:,j])
    Xfj = Xm[id,:][:,np.hstack((range(q),j))]
    covm = np.cov(Xfj, rowvar = False, ddof = 0)
    Q = covm[-1,range(q)] #row vector
    P = np.matmul(Q, np.linalg.inv(covm[:q,:q]))
    S[j,range(q)]  = np.matmul(P, S[:q,:q])

    idj = ~np.isnan(Xm[:,j])
    Xj = Xm[idj,j]
    mu[j,:] =  np.nanmean(Xm[:,j], axis = 0)
    S[j,j] = sum((Xj - mu[j])**2) /len(Xj)

    S[j, range(q,j)] = np.array([dper_sigij1Cl(Xm, mu, i,j, S[i,i], S[j,j]) for i in range(q,j)]).flatten()
    S[:,j] = S[j, :].T
  return mu, S

def dper_sigij1Cl(X, mus, i,j, sigii, sigjj):
        '''
        X: input, should be a numpy array
        y: label
        G: number of classes
        i, j: index of the column
        sigii: sigma_ii
        sigjj: sigma_jj
        '''
        epsilon = 1e-5 # define epsilon to put r down to 0 if r < epsilon
        n,p = X.shape[0], X.shape[1]

        mat = X[:,[i,j]]

        # drop rows with NA
        idx = ~np.isnan(mat).any(axis=1)
        mat = mat[idx]

        A = len(mat)
        scaled_mat = mat-mus[[i,j]].T
        scaled_mat = np.vstack(scaled_mat)
        s11 = sum(scaled_mat[:,0]**2)
        s22 = sum(scaled_mat[:,1]**2)
        s12 = sum(scaled_mat[:,0]*scaled_mat[:,1])

        B = sigii*sigjj*A - s22 * sigii - s11 * sigjj
        coefficient = [-A, s12, B, s12*sigii*sigjj]
        r = np.roots(coefficient)

        r = r[abs(np.imag(r)) < epsilon]
        r = np.real(r)
        r[abs(r) < epsilon] = 0

        if len(r)>1:
          condi_var = sigjj - r**2/sigii
          # print('condi_var',condi_var)
          eta = -A*np.log(condi_var)-(sigjj-2*r/sigii*s12 +
                                      r**2/sigii**2*s11)/condi_var
          # if condi_var <0 then eta = NA. in practice, it's impossible for cov to be negative
          #  therefore, we drop NA elements of eta
          r = r[eta == max(eta[~np.isnan(eta)])]

        if len(r) > 1:
            r = r[np.abs(r-s12/A).argmin()] # select r that is closet to w[0,1]

        return r

In [ ]:
def l2err_inv(Strue, S):
    p = S.shape[0]
    return np.log(norm(inv(Strue)-inv(S)))

def l2err(Strue, S):
    p = S.shape[0]
    return np.log(norm((Strue)-(S)) / (p*p))

def normalize_data(X):
  scaler = StandardScaler()
  scaler.fit(X)
  return scaler.transform(X)

In [ ]:
def experiment(X,y, n, missing_rate):
    G = len(np.unique(y))
    S0=np.cov(X.T)
    #print(S0.shape)
    err = []
    i_err=[]
    for i in range(n):
        mu_0=np.array([np.mean(X[y==g,:])  for g in np.unique(y) ]).T
        Xm0 = generate_nan(X, [0,1], missing_rate)
        Xm=Xm0
        muPhf, SPhf = PHF(Xm, y, G)

        muDper, SDper = dper(Xm, y, G)

        XMice= IterativeImputer(max_iter=100).fit(Xm).transform(Xm)
        SMice =  sum([sum(y==g)*np.cov(XMice[y==g, :], rowvar = False) for g in range(G)])/len(y)

        Xm_copy= pd.DataFrame.from_records(Xm)
        Missf= MissForest()
        XMissf_df = Missf.fit_transform(Xm_copy)
        XMissf= XMissf_df.to_numpy()
        SMissf =  sum([sum(y==g)*np.cov(XMissf[y==g, :], rowvar = False) for g in range(G)])/len(y)

        XSoft =  SoftImpute(max_iters = 100, verbose = False).fit_transform(Xm)
        SSoft =  sum([sum(y==g)*np.cov(XSoft[y==g, :], rowvar = False) for g in range(G)])/len(y)

#       Xxgb = XGBImputer().fit_transform(Xm)
#       Sxgb = sum([sum(y==g)*np.cov(Xxgb[y==g, :], rowvar = False) for g in range(G)])/len(y)

        i_err.append(np.array([l2err_inv(S0, SPhf), l2err_inv(S0, SDper),
                             l2err_inv(S0, SMice), l2err_inv(S0, SMissf),
                             l2err_inv(S0, SSoft)]))

        err.append(np.array([l2err(S0, SPhf), l2err(S0, SDper),
                             l2err(S0, SMice), l2err(S0, SMissf),
                             l2err(S0, SSoft)]))
    return i_err, err

##Experiment on simulated data

In [ ]:
# S0 = np.array([[1.,0.15,0.7,0.45],[0.15,1.,0.12,0.4],[0.7,0.12,1.,0.15],[0.45,0.4,0.15,1.]])
S0 = np.array([[1.,0.15,0.7,0.45],[0.15,1.,0.2,0.4],[0.7,0.2,1.,0.15],[0.45,0.4,0.15,1.]])
def simulation(n, missing_rate):
    G, n_per_class = 4, 100
    mu_1, mu_2 = np.array([1.5,2,1.7,3]), np.array([1,-2,1.5,-3])
    mu_3, mu_4 = np.array([1,3,1.7,1]), np.array([0,2,5,-1])
    mu0 = np.vstack((mu_1,mu_2,mu_3,mu_4)).T

    err = []
    i_err=[]
    for i in range(n):
        X_1 = np.random.multivariate_normal(mu_1,S0,n_per_class)
        #print(X_1.shape)
        X_2 = np.random.multivariate_normal(mu_2,S0,n_per_class)
        X_3 = np.random.multivariate_normal(mu_3,S0,n_per_class)
        X_4 = np.random.multivariate_normal(mu_4,S0,n_per_class)
        X = np.vstack((X_1,X_2, X_3, X_4))
        #print(X.shape)
        y = np.hstack((np.repeat(0,n_per_class), np.repeat(1,n_per_class),
                        np.repeat(2,n_per_class),np.repeat(3,n_per_class)))
        #print(y.shape)
        Xm0 = generate_nan(X, [0,1] , missing_rate)
        Xm=Xm0
        muPhf, SPhf = PHF(Xm, y, G)

        muDper, SDper = dper(Xm, y, G)

        XMice= IterativeImputer(max_iter=100).fit(Xm).transform(Xm)
        SMice =  sum([sum(y==g)*np.cov(XMice[y==g, :], rowvar = False) for g in range(G)])/len(y)

        Xm_copy= pd.DataFrame.from_records(Xm)
        Missf= MissForest()
        XMissf_df = Missf.fit_transform(Xm_copy)
        XMissf= XMissf_df.to_numpy()
        SMissf =  sum([sum(y==g)*np.cov(XMissf[y==g, :], rowvar = False) for g in range(G)])/len(y)

        XSoft =  SoftImpute(max_iters = 100, verbose = False).fit_transform(Xm)
        SSoft =  sum([sum(y==g)*np.cov(XSoft[y==g, :], rowvar = False) for g in range(G)])/len(y)

#         Xxgb = XGBImputer().fit_transform(Xm)
#         Sxgb = sum([sum(y==g)*np.cov(Xxgb[y==g, :], rowvar = False) for g in range(G)])/len(y)

        i_err.append(np.array([l2err_inv(S0, SPhf), l2err_inv(S0, SDper),
                             l2err_inv(S0, SMice), l2err_inv(S0, SMissf),
                             l2err_inv(S0, SSoft)]))
        err.append(np.array([l2err(S0, SPhf), l2err(S0, SDper),
                             l2err(S0, SMice), l2err(S0, SMissf),
                             l2err(S0, SSoft)]))
    return i_err, err

In [ ]:
print(norm(S0).round(3))
print(norm(inv(S0)).round(3))
print(np.linalg.det(S0).round(3))
print(np.linalg.det(inv(S0)).round(3))
print(np.linalg.cond(S0))

2.424
5.289
0.297
3.367
10.218770365918102


In [ ]:
num = 1000
e_inv20,e20 = simulation(num, missing_rate=.2)
e_inv40,e40 = simulation(num, missing_rate=.4)
e_inv60,e60 = simulation(num, missing_rate=.6)
e_inv80,e80 = simulation(num, missing_rate=.8)

Kết quả truyền trực tuyến bị cắt bớt đến 5000 dòng cuối.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with

In [ ]:
print('err of PHF, DPER, Mice, MissForest, Soft-Impute')
np.vstack((np.mean(e20, axis = 0), np.mean(e40, axis = 0),
          np.mean(e60, axis = 0),np.mean(e80, axis = 0))).round(3)

err of PHF, DPER, Mice, MissForest, Soft-Impute


array([[0.015, 0.015, 0.025, 0.023, 0.043],
       [0.016, 0.016, 0.042, 0.041, 0.067],
       [0.017, 0.018, 0.057, 0.062, 0.079],
       [0.019, 0.019, 0.07 , 0.076, 0.08 ]])

In [ ]:
print('std of PHF, DPER, Mice, MissForest, Soft-Impute')
np.vstack((np.std(e20, axis = 0), np.std(e40, axis = 0),
          np.std(e60, axis = 0),np.std(e80, axis = 0))).round(3)

std of PHF, DPER, Mice, MissForest, Soft-Impute


array([[0.005, 0.005, 0.006, 0.006, 0.007],
       [0.005, 0.005, 0.007, 0.012, 0.006],
       [0.005, 0.005, 0.008, 0.017, 0.006],
       [0.006, 0.006, 0.009, 0.019, 0.006]])

In [ ]:
print('inv err of PHF, DPER, Mice, MissForest, Soft-Impute')
np.vstack((np.mean(e_inv20, axis = 0), np.mean(e_inv40, axis = 0),
          np.mean(e_inv60, axis = 0),np.mean(e_inv80,axis = 0))).round(3)

inv err of PHF, DPER, Mice, MissForest, Soft-Impute


array([[0.041, 0.037, 0.081, 0.067, 0.167],
       [0.056, 0.046, 0.103, 0.098, 0.202],
       [0.081, 0.062, 0.152, 0.118, 0.216],
       [0.116, 0.085, 0.273, 0.144, 0.222]])

In [ ]:
print('inv std of PHF, DPER, Mice, MissForest, Soft-Impute')
np.vstack((np.std(e_inv20, axis = 0), np.std(e_inv40, axis = 0),
          np.std(e_inv60, axis = 0),np.std(e_inv80,axis = 0))).round(3)

inv std of PHF, DPER, Mice, MissForest, Soft-Impute


array([[0.022, 0.018, 0.014, 0.019, 0.012],
       [0.045, 0.027, 0.013, 0.017, 0.009],
       [0.11 , 0.053, 0.034, 0.017, 0.008],
       [0.264, 0.173, 0.08 , 0.025, 0.008]])